export const ROUTE_PATHS = {
  inici: '/',
  aterratge: '/aterratge',
  autenticacio: '/acces',
  tauler: '/tauler',
  conversa: '/xat',
  espaiDeTreball: '/xat/espai-treball',
  cerca: '/cercar',
  alertes: '/alertes',
  municipis: '/municipis',
  regidors: '/regidors',
  reputacio: '/reputacio',
  intelLigencia: '/intel-ligencia',
  parlament: '/parlament',
  informes: '/informes',
  recepcio: '/recepcio',
  configuracio: '/configuracio',
  subscripcions: '/subscripcions',
  administracio: '/administracio',
  actes: '/actes',
  legal: '/legal',
} as const;

export const ROUTE_ALIASES: Record<string, string> = {
  '/landing': ROUTE_PATHS.aterratge,
  '/login': ROUTE_PATHS.autenticacio,
  '/dashboard': ROUTE_PATHS.tauler,
  '/chat': ROUTE_PATHS.conversa,
  '/chat/workspace': ROUTE_PATHS.espaiDeTreball,
  '/buscar': ROUTE_PATHS.cerca,
  '/alertas': ROUTE_PATHS.alertes,
  '/municipios': ROUTE_PATHS.municipis,
  '/regidors': ROUTE_PATHS.regidors,
  '/reputacio': ROUTE_PATHS.reputacio,
  '/intel': ROUTE_PATHS.intelLigencia,
  '/parlament': ROUTE_PATHS.parlament,
  '/informes': ROUTE_PATHS.informes,
  '/recepcion': ROUTE_PATHS.recepcio,
  '/settings': ROUTE_PATHS.configuracio,
  '/suscripciones': ROUTE_PATHS.subscripcions,
  '/admin': ROUTE_PATHS.administracio,
  '/actas': ROUTE_PATHS.actes,
};

export const CATALAN_ROUTE_SEGMENTS = new Set([
  '',
  'acces',
  'actes',
  'administracio',
  'alertes',
  'aterratge',
  'cercar',
  'configuracio',
  'informes',
  'inici',
  'intel-ligencia',
  'legal',
  'municipis',
  'parlament',
  'recepcio',
  'regidors',
  'reputacio',
  'subscripcions',
  'tauler',
  'xat',
  'espai-treball',
]);
